apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: message-queue
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: amqp://guest:guest@localhost:5672
  - name: topic
    value: sensor-data
  - name: durable
    value: true
  - name: deleteWhenUnused
    value: false
  - name: prefetchCount
    value: 0
  - name: contentType
    value: "plain/text"
  - name: exchangeKind
    value: direct
